on:
    push:
        branches:
            master

name: Render-Book-from-master

jobs:
    bookdown:
        name: Render-Book
        runs-on: ubuntu-latest
        if: "!(contains(github.event.head_commit.message, 'ci skip')||contains(github.event.head_commit.message, 'skip ci'))"
        steps:
            #- name: Install libcurl
            #  install: libcurl4-openssl-dev
            - uses: actions/checkout@v2
            - uses: r-lib/actions/setup-r@v1
            - uses: r-lib/actions/setup-pandoc@v1
            - name: Query dependencies
              run:
                  Rscript -e "install.packages('remotes')" -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds', version = 2)"

            - name: Cache R packages
              uses: actions/cache@v1
              with:
                  path: ${{ env.R_LIBS_USER }}
                  key: ${{ runner.os }}-r-${{ hashFiles('depends.Rds') }}
                  restore-keys: ${{ runner.os }}-r-


            - name: Install dependencies
              run:
                  Rscript -e "library(remotes)" -e "deps <- readRDS('depends.Rds')" -e "deps[['installed']] <- vapply(deps[['package']], remotes:::local_sha, character(1))" -e "update(deps)"

            - name: Render Book
              run: Rscript -e 'bookdown::render_book("index.Rmd")'
            - name: Commit results
              run: |
                  cd docs
                  git init
                  git add .
                  git commit -m 'update book'
                  git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:gh-pages --force
